apiVersion: v1
data:
  parsers.conf: |
      [PARSER]
          Name        docker
          Format      json
          Time_Key    time
          Time_Format %Y-%m-%dT%H:%M:%S.%L
          Time_Keep   On

  fluent-bit.conf: |
      [SERVICE]
          flush 1
          log_level info
          Parsers_File  parsers.conf

      [INPUT]
          Name   tail
          Path   /var/lib/docker/containers/*/*.log
          Parser docker
          Refresh_Interval 30
          Ignore_Older 6h
          Docker_Mode  On
          Tag source.docker.<container_id>
          Tag_Regex (.*\/(?<container_id>.*)-json\.log)

      [FILTER]
          Name   lua
          Match  source.docker.*
          script /fluent-bit/bin/docker-metadata.lua
          call   encrich_with_docker_metadata

      [INPUT]
          name            node_exporter_metrics
          tag             node_metrics
          scrape_interval 180
          path.procfs     /host/proc
          path.sysfs      /host/sys

      [OUTPUT]
          Name                 opentelemetry
          Match                *
          Host                 collector
          Port                 3030
          metrics_uri          /v1/metrics
          logs_uri             /v1/logs
          traces_uri           /v1/traces
          Log_response_payload True
          tls                  off
          tls.verify           off
          # add user-defined labels
          add_label            app fluent-bit
          add_label            color blue
          
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  creationTimestamp: null
  labels:
    io.kompose.service: fluentbit
  name: fluentbit-cm1
