apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --file ./kbot/otel/docker-compose.yaml --out ./kbot-monitoring/helm --chart --volumes configMap
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: kbot
  name: kbot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: kbot
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert --file ./kbot/otel/docker-compose.yaml --out ./kbot-monitoring/helm --chart --volumes configMap
        kompose.version: 1.28.0 (c4137012e)
      creationTimestamp: null
      labels:
        io.kompose.network/otel-default: "true"
        io.kompose.service: kbot
    spec:
      containers:
        - env:
            - name: METRICS_HOST
              value: collector:4317
            - name: TELE_TOKEN
              value: ${TELE_TOKEN}
          image: darbooshka/kbot:v1.0.6-9fbdfc4-amd64
          name: kbot
          resources: {}
      restartPolicy: Always
status: {}
