apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --file ./kbot/otel/docker-compose.yaml --out ./kbot-monitoring/helm --chart --volumes configMap
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.service: loki
  name: loki
spec:
  ports:
    - name: "3100"
      port: 3100
      targetPort: 3100
    - name: "9096-grpc"
      port: 9096
      targetPort: 9096
    - name: "9093-alert-manager"
      port: 9093
      targetPort: 9093

  selector:
    io.kompose.service: loki
status:
  loadBalancer: {}
